version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: chatbot-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgre_chatbot_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgre_chatbot_db:
    driver: local